name: dominoes

dependencies:
  - base

library:
  exposed-modules: Dominoes
  source-dirs: src
  dependencies:
    - containers
    - lens
    - mtl
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - dominoes
      - hspec
